import React from "react";
import SEO from "../components/SEO";

const Terms = () => {
  return (
    <div className="pt-24 min-h-screen bg-gradient-to-b from-[#030712] via-[#0B0F19] to-[#030712] text-slate-100 selection:bg-amber-400 selection:text-black">
      <SEO
        title="Terms of Service - PANTHM AI Labs"
        description="Terms of Service for PANTHM AI Labs. Review details on intellectual property, use of services, liability limits, and general terms of engagement."
        keywords="terms of service, legal terms, PANTHM AI Labs, user agreement"
        url="https://panthm.com/terms"
      />

      <div className="wrapper max-w-4xl mx-auto px-6 py-12 md:py-20 space-y-12">
        <div className="text-center space-y-4">
          <h1 className="text-4xl md:text-5xl font-extrabold tracking-tight leading-tight">
            Terms of Service
          </h1>
          <p className="text-amber-400 font-semibold uppercase tracking-wider text-sm">
            Effective Date: July 15, 2026
          </p>
        </div>

        <div className="prose prose-invert max-w-none space-y-8 bg-[#0B0F19]/60 backdrop-blur-xl border border-white/5 p-8 md:p-12 rounded-3xl shadow-[0_0_30px_rgba(0,0,0,0.3)]">
          
          <section className="space-y-3">
            <h2 className="text-xl md:text-2xl font-bold text-slate-100 flex items-center gap-3">
              <span className="text-amber-400 font-mono">1.</span> ACCEPTANCE OF TERMS
            </h2>
            <p className="text-slate-300 leading-relaxed text-sm md:text-base">
              By accessing or using the services provided by PANTHM AI Labs ("PANTHM", "we", "us", or "our"), including our website at https://panthm.com, software applications, and consulting services, you agree to comply with and be bound by these Terms of Service. If you do not agree to these terms, please do not use our services.
            </p>
          </section>

          <div className="h-[1px] bg-white/5"></div>

          <section className="space-y-3">
            <h2 className="text-xl md:text-2xl font-bold text-slate-100 flex items-center gap-3">
              <span className="text-amber-400 font-mono">2.</span> SERVICES AND ENGAGEMENTS
            </h2>
            <p className="text-slate-300 leading-relaxed text-sm md:text-base">
              PANTHM AI Labs specializes in custom AI calling, voice AI agents, custom software engineering, and digital workflow automation. Specific scope, deliverables, timelines, and payment structures for custom projects are defined in individual statements of work (SOW) or master service agreements (MSA) executed separately.
            </p>
          </section>

          <div className="h-[1px] bg-white/5"></div>

          <section className="space-y-3">
            <h2 className="text-xl md:text-2xl font-bold text-slate-100 flex items-center gap-3">
              <span className="text-amber-400 font-mono">3.</span> INTELLECTUAL PROPERTY
            </h2>
            <p className="text-slate-300 leading-relaxed text-sm md:text-base">
              All materials, text, graphics, branding, software code, and systems generated by PANTHM on this website are the intellectual property of PANTHM AI Labs unless otherwise agreed. For custom client engagements, ownership of deliverables is transferred upon full settlement of all contractual invoices.
            </p>
          </section>

          <div className="h-[1px] bg-white/5"></div>

          <section className="space-y-3">
            <h2 className="text-xl md:text-2xl font-bold text-slate-100 flex items-center gap-3">
              <span className="text-amber-400 font-mono">4.</span> LIMITATION OF LIABILITY
            </h2>
            <p className="text-slate-300 leading-relaxed text-sm md:text-base">
              To the maximum extent permitted by applicable law, PANTHM AI Labs shall not be liable for any direct, indirect, incidental, special, or consequential damages resulting from the use or inability to use our services, server downtime, API limits, or data loss.
            </p>
          </section>

          <div className="h-[1px] bg-white/5"></div>

          <section className="space-y-3">
            <h2 className="text-xl md:text-2xl font-bold text-slate-100 flex items-center gap-3">
              <span className="text-amber-400 font-mono">5.</span> GOVERNING LAW
            </h2>
            <p className="text-slate-300 leading-relaxed text-sm md:text-base">
              These Terms of Service are governed by and construed in accordance with the laws of India. Any disputes arising from these terms or your use of our services shall be subject to the exclusive jurisdiction of the courts in Pune, Maharashtra, India.
            </p>
          </section>

          <div className="h-[1px] bg-white/5"></div>

          <section className="space-y-3">
            <h2 className="text-xl md:text-2xl font-bold text-slate-100 flex items-center gap-3">
              <span className="text-amber-400 font-mono">6.</span> CONTACT INFO
            </h2>
            <p className="text-slate-300 leading-relaxed text-sm md:text-base">
              If you have any questions regarding these Terms of Service, please write to us at{" "}
              <a 
                href="mailto:admin@panthm.com" 
                className="text-amber-400 hover:text-amber-300 underline transition-colors"
              >
                admin@panthm.com
              </a>
              .
            </p>
          </section>

        </div>
      </div>
    </div>
  );
};

export default Terms;
